#!/bin/bash

if [ -z "$1" ]; then
    read -p "Type n: " n
else
    n=$1
fi
case $n in
    [0,1]*)
    ;;
    *)
        a=0
        b=1
        for i in `seq 2 $n`;
        do
            c=$b
            b=$((a+b))
            a=$c
        done
        n=$b
esac
echo $n
